# Generated by Django 4.0.3 on 2022-04-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_deal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
